<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>03923dfb-0658-4450-b27f-fc36e61f4f80</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Monitor.OpenTelemetry.AspNetCore" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.Azure.SignalR" />
    <PackageReference Include="Microsoft.Identity.Web" />
    <PackageReference Include="Microsoft.OpenApi" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpportunityEngineering.Application\OpportunityEngineering.Application.csproj" />
    <ProjectReference Include="..\OpportunityEngineering.Infrastructure\OpportunityEngineering.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="guardrails\policy.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
